"""Prints the dataset observations as markdown.

    python analysis/explore_feed.py > docs/dataset-observations.md

The arithmetic lives in feed_stats.py, which analysis/explore_feed.ipynb also imports.
The notebook is the readable version, with charts; this is the committed text one.
Standard library only, so it runs with no install.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import feed_stats as fs  # noqa: E402


def main() -> None:
    records = fs.load()
    mmsis = fs.vessels(records)

    print("# Dataset Observations")
    print()
    print("Generated by `analysis/explore_feed.py` from `ship_positions.json`.")
    print("Regenerate with `python analysis/explore_feed.py > docs/dataset-observations.md`.")
    print("For the same analysis with charts, open `analysis/explore_feed.ipynb`.")
    print()
    print("These are observations about the supplied data, recorded because they shaped")
    print("design decisions. They describe what the file contains, not what it should.")

    shape = fs.shape(records)
    print("\n## Shape\n")
    print(f"- **{shape['records']:,} records**, {shape['vessels']} vessels, "
          f"{shape['distinct_station_ids']:,} distinct `stationId`.")
    print(f"- Spanning **{shape['span_hours']:.1f} hours**, {shape['first']} to {shape['last']} UTC.")
    print(f"- Every record carries all {shape['fields']} fields; none is null.")
    print()
    print("| MMSI | records | latitude | longitude |")
    print("| --- | --- | --- | --- |")
    for mmsi in mmsis:
        rows = [r for r in records if r["mmsi"] == mmsi]
        lats = [r["lat"] for r in rows]
        lons = [r["lon"] for r in rows]
        print(f"| {mmsi} | {len(rows)} | {min(lats):.2f}–{max(lats):.2f} "
              f"| {min(lons):.2f}–{max(lons):.2f} |")

    facts = fs.report_id_facts(records)
    print("\n## `stationId` is a record identifier, not a receiving station\n")
    print(f"- Unique across all {len(records):,} records: **{facts['unique']}**.")
    print(f"- Range {facts['minimum']}–{facts['maximum']}, with gaps.")
    print(f"- Strictly ascending in file order: **{facts['ascending_in_file_order']}**.")
    print()
    print("No value repeats even once across 18 hours and 3 vessels, which is not how a")
    print("receiving station behaves. It is treated as the Report ID (ADR-0001).")

    conflicts = fs.conflicts(records)
    print("\n## `(mmsi, timestamp)` is not unique, and the duplicates conflict\n")
    print(f"- Only **{conflicts['distinct_pairs']} distinct `(mmsi, timestamp)` pairs** "
          f"across {len(records):,} records.")
    print(f"- **{conflicts['repeated_keys']} of those keys carry more than one record**, "
          f"and **{conflicts['exact_duplicates']} of them are exact duplicates**.")
    print(f"- The busiest single key carries **{conflicts['busiest_key_size']} records**.")
    separations = conflicts["separations_km"]
    print(f"- Separation between the first two of each: median "
          f"{separations[len(separations) // 2]:.0f} km, max **{max(separations):.0f} km**.")
    print(f"- Keying on `(mmsi, timestamp)` would discard "
          f"**{conflicts['records_lost']:,} records ({conflicts['share_lost']:.1%})**.")
    print()
    print("The widest disagreement, one vessel at one second:")
    print()
    print("```")
    for record in conflicts["widest_pair"]:
        print(f"mmsi {record['mmsi']} @ {record['timestamp']} -> "
              f"stationId {record['stationId']:>4}, {record['lat']:.5f}, "
              f"{record['lon']:.5f}, speed {record['speed'] / 10:.1f} kn")
    print("```")
    print()
    print("Both are kept. The store records observations rather than adjudicating between")
    print("them (ADR-0001).")

    times = fs.timestamp_facts(records)
    print("\n## Reported Time is heavily degenerate\n")
    print(f"- Only **{times['distinct']} distinct values** across {len(records):,} records.")
    print("- Every gap between consecutive values is a multiple of 60s: "
          f"**{times['all_gaps_minute_multiples']}**.")
    print(f"- The busiest single value, {times['busiest']} ({times['busiest_label']}), "
          f"carries **{times['busiest_count']} records**.")
    print()
    for mmsi in mmsis:
        rows = [r for r in records if r["mmsi"] == mmsi and r["timestamp"] == times["busiest"]]
        if not rows:
            continue
        lats = [r["lat"] for r in rows]
        lons = [r["lon"] for r in rows]
        print(f"  - At that one second, MMSI {mmsi} has {len(rows)} records spanning "
              f"lat {min(lats):.2f}–{max(lats):.2f}, lon {min(lons):.2f}–{max(lons):.2f}.")
    print()
    print("A one-minute time filter can therefore return hundreds of reports scattered")
    print("across the Mediterranean. This is a property of the data, not of the API.")
    print("It also makes real-time replay undefined: there are no inter-arrival gaps to honour.")

    print("\n## Ordering by `stationId` recovers coherent voyages; by timestamp it does not\n")
    print("Consecutive-hop distance along each vessel's track under each ordering.")
    print()
    print("| MMSI | ordering | total path | median hop | p95 hop |")
    print("| --- | --- | --- | --- | --- |")
    for row in fs.ordering_comparison(records):
        print(f"| {row['mmsi']} | {row['ordering']} | {row['total_path_km']:,.0f} km "
              f"| {row['median_hop_km']:.2f} km | {row['p95_hop_km']:.2f} km |")
    print()
    print("Independent corroboration: taking each report's own reported Speed, the time it")
    print("would need to cover the distance to the next report in `stationId` order is")
    print()
    for mmsi, seconds in fs.implied_intervals(records).items():
        print(f"  - MMSI {mmsi}: median **{seconds:.0f} s**")
    print()
    print("Two of the three land on the 60-second grid the timestamps use, which is what")
    print("you would expect if `stationId` is the true receipt sequence. MMSI 247039300")
    print("stays incoherent under both orderings, consistent with two vessels sharing one")
    print("MMSI - a real AIS phenomenon. Not investigated further; it changes no decision.")

    fields = fs.field_ranges(records)
    print("\n## Field ranges\n")
    print("| field | observed | note |")
    print("| --- | --- | --- |")
    print(f"| `speed` | {fields['speed'][0]}–{fields['speed'][1]} | knots x10; "
          f"max is {fields['speed'][1] / 10:.1f} kn |")
    print(f"| `course` | {fields['course'][0]}–{fields['course'][1]} | whole degrees, "
          "not the decidegrees AIS uses on the wire |")
    print(f"| `heading` | {fields['heading'][0]}–{fields['heading'][1]} | whole degrees |")
    print(f"| `rot` | {fields['rot']} | the empty string in every record |")
    print(f"| `status` | {fields['status']} | navigational status |")
    print()
    print("`rot` never carries a value, so its column type comes from the AIS specification")
    print("(signed, -128..127) rather than from the data. A non-nullable column would")
    print("reject the entire dataset (ADR-0002).")


if __name__ == "__main__":
    main()
