"""Reproduces the dataset observations that shaped this project's design.

Standard library only, so it runs anywhere with no install:

    python analysis/explore_feed.py > docs/dataset-observations.md

Every figure quoted in the README and in the ADRs comes from here. Nothing in this
file is imported by the application; it exists so the claims can be checked.
"""

from __future__ import annotations

import json
import math
import statistics
import sys
from collections import Counter, defaultdict
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

FEED = Path(__file__).resolve().parent.parent / "ship_positions.json"
KM_PER_NAUTICAL_MILE = 1.852


def haversine_km(a: dict[str, Any], b: dict[str, Any]) -> float:
    radius = 6371.0
    lat1, lat2 = math.radians(a["lat"]), math.radians(b["lat"])
    dlat = lat2 - lat1
    dlon = math.radians(b["lon"] - a["lon"])
    h = math.sin(dlat / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin(dlon / 2) ** 2
    return 2 * radius * math.asin(math.sqrt(h))


def utc(epoch: int) -> str:
    return datetime.fromtimestamp(epoch, UTC).strftime("%Y-%m-%d %H:%M")


def section(title: str) -> None:
    print(f"\n## {title}\n")


def main() -> None:
    records: list[dict[str, Any]] = json.loads(FEED.read_text())
    mmsis = sorted({r["mmsi"] for r in records})
    timestamps = [r["timestamp"] for r in records]
    station_ids = [r["stationId"] for r in records]

    print("# Dataset Observations")
    print()
    print(f"Generated by `analysis/explore_feed.py` from `{FEED.name}`.")
    print("Regenerate with `python analysis/explore_feed.py > docs/dataset-observations.md`.")
    print()
    print("These are observations about the supplied data, recorded because they shaped")
    print("design decisions. They describe what the file contains, not what it should.")

    # ------------------------------------------------------------------ shape
    section("Shape")
    span_hours = (max(timestamps) - min(timestamps)) / 3600
    print(f"- **{len(records):,} records**, {len(mmsis)} vessels, {len(set(station_ids)):,} distinct `stationId`.")
    print(f"- Spanning **{span_hours:.1f} hours**, {utc(min(timestamps))} to {utc(max(timestamps))} UTC.")
    print(f"- Every record carries all {len(records[0])} fields; none is null.")
    print()
    print("| MMSI | records | latitude | longitude |")
    print("| --- | --- | --- | --- |")
    for mmsi in mmsis:
        rows = [r for r in records if r["mmsi"] == mmsi]
        lats = [r["lat"] for r in rows]
        lons = [r["lon"] for r in rows]
        print(
            f"| {mmsi} | {len(rows)} | {min(lats):.2f}–{max(lats):.2f} "
            f"| {min(lons):.2f}–{max(lons):.2f} |"
        )

    # -------------------------------------------------------------- report id
    section("`stationId` is a record identifier, not a receiving station")
    unique = len(set(station_ids)) == len(records)
    print(f"- Unique across all {len(records):,} records: **{unique}**.")
    print(f"- Range {min(station_ids)}–{max(station_ids)}, with gaps.")
    print(f"- Strictly ascending in file order: **{station_ids == sorted(station_ids)}**.")
    print()
    print("No value repeats even once across 18 hours and 3 vessels, which is not how a")
    print("receiving station behaves. It is treated as the Report ID (ADR-0001).")

    # ---------------------------------------------------------- conflicts
    section("`(mmsi, timestamp)` is not unique, and the duplicates conflict")
    grouped: dict[tuple[int, int], list[dict[str, Any]]] = defaultdict(list)
    for record in records:
        grouped[(record["mmsi"], record["timestamp"])].append(record)
    conflicts = {k: v for k, v in grouped.items() if len(v) > 1}
    exact = sum(1 for v in conflicts.values() if all(x == v[0] for x in v))
    separations = sorted(haversine_km(v[0], v[1]) for v in conflicts.values())
    lost = len(records) - len(grouped)
    print(f"- Only **{len(grouped)} distinct `(mmsi, timestamp)` pairs** across {len(records):,} records.")
    print(f"- **{len(conflicts)} of those keys carry more than one record**, and **{exact} of them are exact duplicates**.")
    print(f"- The busiest single key carries **{max(len(v) for v in conflicts.values())} records**.")
    print(
        f"- Separation between the first two of each: median {statistics.median(separations):.0f} km, "
        f"max **{max(separations):.0f} km**."
    )
    print(f"- Keying on `(mmsi, timestamp)` would discard **{lost} records ({lost / len(records):.1%})**.")
    print()
    worst = max(conflicts.values(), key=lambda v: haversine_km(v[0], v[1]))
    print("The widest disagreement, one vessel at one second:")
    print()
    print("```")
    for record in worst[:2]:
        print(
            f"mmsi {record['mmsi']} @ {record['timestamp']} -> stationId {record['stationId']:>4}, "
            f"{record['lat']:.5f}, {record['lon']:.5f}, speed {record['speed'] / 10:.1f} kn"
        )
    print("```")
    print()
    print("Both are kept. The store records observations rather than adjudicating between")
    print("them (ADR-0001).")

    # ------------------------------------------------------- timestamp
    section("Reported Time is heavily degenerate")
    per_timestamp = Counter(timestamps)
    gaps = {b - a for a, b in zip(sorted(set(timestamps)), sorted(set(timestamps))[1:])}
    busiest, busiest_count = per_timestamp.most_common(1)[0]
    print(f"- Only **{len(set(timestamps))} distinct values** across {len(records):,} records.")
    print(f"- Every gap between consecutive values is a multiple of 60s: **{all(g % 60 == 0 for g in gaps)}**.")
    print(f"- The busiest single value, {busiest} ({utc(busiest)}), carries **{busiest_count} records**.")
    print()
    for mmsi in mmsis:
        rows = [r for r in records if r["mmsi"] == mmsi and r["timestamp"] == busiest]
        if not rows:
            continue
        lats = [r["lat"] for r in rows]
        lons = [r["lon"] for r in rows]
        print(
            f"  - At that one second, MMSI {mmsi} has {len(rows)} records spanning "
            f"lat {min(lats):.2f}–{max(lats):.2f}, lon {min(lons):.2f}–{max(lons):.2f}."
        )
    print()
    print("A one-minute time filter can therefore return hundreds of reports scattered")
    print("across the Mediterranean. This is a property of the data, not of the API.")
    print("It also makes real-time replay undefined: there are no inter-arrival gaps to honour.")

    # -------------------------------------------------------- ordering
    section("Ordering by `stationId` recovers coherent voyages; by timestamp it does not")
    print("Consecutive-hop distance along each vessel's track under each ordering.")
    print()
    print("| MMSI | ordering | total path | median hop | p95 hop |")
    print("| --- | --- | --- | --- | --- |")
    for mmsi in mmsis:
        rows = [r for r in records if r["mmsi"] == mmsi]
        for label, key in (
            ("timestamp", lambda r: (r["timestamp"], r["stationId"])),
            ("stationId", lambda r: r["stationId"]),
        ):
            ordered = sorted(rows, key=key)
            hops = sorted(haversine_km(a, b) for a, b in zip(ordered, ordered[1:]))
            print(
                f"| {mmsi} | {label} | {sum(hops):,.0f} km | {statistics.median(hops):.2f} km "
                f"| {hops[int(0.95 * len(hops))]:.2f} km |"
            )
    print()
    print("Independent corroboration: taking each report's own reported Speed, the time it")
    print("would need to cover the distance to the next report in `stationId` order is")
    print()
    for mmsi in mmsis:
        ordered = sorted((r for r in records if r["mmsi"] == mmsi), key=lambda r: r["stationId"])
        intervals = [
            haversine_km(a, b) / KM_PER_NAUTICAL_MILE / (a["speed"] / 10) * 3600
            for a, b in zip(ordered, ordered[1:])
            if a["speed"] > 5
        ]
        print(f"  - MMSI {mmsi}: median **{statistics.median(intervals):.0f} s**")
    print()
    print("Two of the three land on the 60-second grid the timestamps use, which is what")
    print("you would expect if `stationId` is the true receipt sequence. MMSI 247039300")
    print("stays incoherent under both orderings, consistent with two vessels sharing one")
    print("MMSI - a real AIS phenomenon. Not investigated further; it changes no decision.")

    # ---------------------------------------------------------- fields
    section("Field ranges")
    print("| field | observed | note |")
    print("| --- | --- | --- |")
    speeds = [r["speed"] for r in records]
    courses = [r["course"] for r in records]
    headings = [r["heading"] for r in records]
    rots = Counter(r["rot"] for r in records)
    statuses = Counter(r["status"] for r in records)
    print(f"| `speed` | {min(speeds)}–{max(speeds)} | knots x10; max is {max(speeds) / 10:.1f} kn |")
    print(f"| `course` | {min(courses)}–{max(courses)} | whole degrees, not the decidegrees AIS uses on the wire |")
    print(f"| `heading` | {min(headings)}–{max(headings)} | whole degrees |")
    print(f"| `rot` | {dict(rots)} | the empty string in every record |")
    print(f"| `status` | {dict(statuses)} | navigational status |")
    print()
    print("`rot` never carries a value, so its column type comes from the AIS specification")
    print("(signed, -128..127) rather than from the data. A non-nullable column would")
    print("reject the entire dataset (ADR-0002).")


if __name__ == "__main__":
    sys.exit(main())
